# Generated by Django 6.0.6 on 2026-06-27 06:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Line",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveSmallIntegerField(default=1, help_text="The line number in the page.")),
                (
                    "type",
                    models.CharField(
                        choices=[("sura_header", "Sura Header"), ("besmella", "Besmella"), ("text", "Text")],
                        default="text",
                        max_length=16,
                    ),
                ),
                (
                    "line_png",
                    models.ImageField(
                        help_text="Final PNG path after coordinates + erase; set on export",
                        null=True,
                        upload_to="lines/",
                    ),
                ),
                ("bbox_x", models.PositiveIntegerField(help_text="The x coordinate of the bounding box.")),
                ("bbox_y", models.PositiveIntegerField(help_text="The y coordinate of the bounding box.")),
                ("bbox_w", models.PositiveIntegerField(help_text="The width of the bounding box.")),
                ("bbox_h", models.PositiveIntegerField(help_text="The height of the bounding box.")),
            ],
            options={
                "verbose_name": "Line",
                "verbose_name_plural": "Lines",
                "db_table": "line",
            },
        ),
        migrations.CreateModel(
            name="Mushaf",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("pdf_file", models.FileField(upload_to="mushafs/")),
                ("pdf_sha256", models.CharField(max_length=64)),
                ("pdf_page_count", models.PositiveSmallIntegerField()),
                (
                    "first_quran_pdf_page",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="PDF physical page index (1-based) of the first logical Quran page."
                    ),
                ),
                (
                    "last_quran_pdf_page",
                    models.PositiveSmallIntegerField(
                        help_text="PDF physical page index (1-based) of the last logical Quran page."
                    ),
                ),
            ],
            options={
                "verbose_name": "Mushaf",
                "verbose_name_plural": "Masahef",
                "db_table": "mushaf",
            },
        ),
        migrations.CreateModel(
            name="Qiraa",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sura",
            fields=[
                ("number", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("transliteration", models.CharField(max_length=32, unique=True)),
                ("name_arabic", models.CharField(max_length=32, unique=True)),
            ],
            options={
                "verbose_name": "Sura",
                "verbose_name_plural": "Suras",
                "db_table": "sura",
            },
        ),
        migrations.CreateModel(
            name="EraseStroke",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brush_size", models.PositiveSmallIntegerField(default=12)),
                (
                    "points",
                    models.JSONField(
                        default=list,
                        help_text=(
                            "A JSON array containing the coordinates of the points in the stroke."
                            "The format is [[x, y], ...]."
                        ),
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="erase_strokes", to="api.line"
                    ),
                ),
            ],
            options={
                "verbose_name": "Erase Stroke",
                "verbose_name_plural": "Erase Strokes",
                "db_table": "erase_stroke",
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page_number",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="The logical page number of the Quran. The first page is 1."
                    ),
                ),
                (
                    "source_pdf_page",
                    models.PositiveSmallIntegerField(help_text="The page number of the source PDF.", null=True),
                ),
                ("bbox_x", models.PositiveIntegerField(help_text="The x coordinate of the bounding box.", null=True)),
                ("bbox_y", models.PositiveIntegerField(help_text="The y coordinate of the bounding box.", null=True)),
                ("bbox_w", models.PositiveIntegerField(help_text="The width of the bounding box.", null=True)),
                ("bbox_h", models.PositiveIntegerField(help_text="The height of the bounding box.", null=True)),
                (
                    "mushaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="api.mushaf"
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "db_table": "page",
            },
        ),
        migrations.AddField(
            model_name="line",
            name="page",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="api.page"),
        ),
        migrations.CreateModel(
            name="ProcessingRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=(
                            "A JSON object containing the settings used for the processing run."
                            "The format is {'setting_name': setting_value}.The settings include padding,"
                            " expected_lines, sura_header_slots, sura_header_threshold, max_sura_headers,"
                            " match_threshold, alternate_horizontal_margin, prefer_acceleration, start_sura,"
                            " start_aya, bounds",
                        ),
                    ),
                ),
                (
                    "page_range_start",
                    models.PositiveSmallIntegerField(
                        help_text=(
                            "The logical page number of the first page of the PDF to process.The first page is 1."
                        )
                    ),
                ),
                (
                    "page_range_end",
                    models.PositiveSmallIntegerField(
                        help_text="The logical page number of the last page of the PDF to process."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("aborted_line_detection", "Aborted Line Detection"),
                            ("error", "Error"),
                        ],
                        default="completed",
                        max_length=32,
                    ),
                ),
                ("abort_info", models.TextField(blank=True, default="")),
                (
                    "mushaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="processing_runs", to="api.mushaf"
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Run",
                "verbose_name_plural": "Processing Runs",
                "db_table": "processing_run",
            },
        ),
        migrations.AddField(
            model_name="page",
            name="last_run",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pages", to="api.processingrun"
            ),
        ),
        migrations.AddField(
            model_name="mushaf",
            name="qiraa",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mushafs", to="api.qiraa"
            ),
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "segment_order",
                    models.PositiveSmallIntegerField(default=1, help_text="The segment number in the line."),
                ),
                ("bbox_x", models.PositiveIntegerField(help_text="The x coordinate of the bounding box.")),
                ("bbox_w", models.PositiveIntegerField(help_text="The width of the bounding box.")),
                (
                    "has_separator",
                    models.BooleanField(default=False, help_text="Whether the segment has a separator or not."),
                ),
                ("aya_number", models.PositiveSmallIntegerField(help_text="The aya number in the sura.", null=True)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="segments", to="api.line"
                    ),
                ),
            ],
            options={
                "verbose_name": "Segment",
                "verbose_name_plural": "Segments",
                "db_table": "segment",
            },
        ),
        migrations.AddField(
            model_name="line",
            name="sura",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lines", to="api.sura"
            ),
        ),
        migrations.CreateModel(
            name="SuraAyaCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.PositiveSmallIntegerField()),
                (
                    "qiraa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sura_aya_counts", to="api.qiraa"
                    ),
                ),
                (
                    "sura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="aya_counts", to="api.sura"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sura Aya Count",
                "verbose_name_plural": "Sura Aya Counts",
                "db_table": "sura_aya_count",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("sura_header", "Sura Header"), ("aya_separator", "Aya Separator")],
                        default="sura_header",
                        max_length=16,
                    ),
                ),
                ("image", models.ImageField(upload_to="templates/")),
                (
                    "ignore_rects",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=(
                            "A JSON object containing the coordinates of the rectangles to ignore in the template"
                            " image.The format is {'x': int, 'y': int, 'width': int, 'height': int}.",
                        ),
                    ),
                ),
                (
                    "mushaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="templates", to="api.mushaf"
                    ),
                ),
            ],
            options={
                "verbose_name": "Template",
                "verbose_name_plural": "Templates",
                "db_table": "template",
            },
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(fields=("mushaf", "page_number"), name="unique_mushaf_page_number"),
        ),
        migrations.AddConstraint(
            model_name="suraayacount",
            constraint=models.UniqueConstraint(fields=("sura", "qiraa"), name="unique_sura_qiraa"),
        ),
        migrations.AddConstraint(
            model_name="template",
            constraint=models.UniqueConstraint(fields=("mushaf", "type"), name="unique_mushaf_type"),
        ),
    ]
