# Generated by Django 6.0.6 on 2026-06-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="reviewed",
            field=models.BooleanField(
                default=False,
                help_text="True once a user has saved this page in review; reset to False on (re)process.",
            ),
        ),
        migrations.AlterField(
            model_name="processingrun",
            name="page_range_start",
            field=models.PositiveSmallIntegerField(
                help_text="The logical page number of the first page of the PDF to process. The first page is 1."
            ),
        ),
        migrations.AlterField(
            model_name="processingrun",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A JSON object containing the settings used for the processing run.The format is {'setting_name': setting_value}.The settings include padding, expected_lines, sura_header_slots, sura_header_threshold, max_sura_headers, match_threshold, alternate_horizontal_margin, prefer_acceleration, start_sura, start_aya, bounds",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="ignore_rects",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A JSON object containing the coordinates of the rectangles to ignore in the template image.The format is {'x': int, 'y': int, 'width': int, 'height': int}.",
            ),
        ),
    ]
