# Generated by Django 6.0.6 on 2026-06-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_countingsystem_remove_suraayacount_unique_sura_qiraa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qiraa',
            options={'verbose_name': 'Qiraa', 'verbose_name_plural': 'Qiraat'},
        ),
        migrations.AlterModelTable(
            name='qiraa',
            table='qiraa',
        ),
    ]
