# Generated by Django 6.0.6 on 2026-06-28 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_qiraa_options_alter_qiraa_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mushaf",
            name="qiraa",
        ),
        migrations.RemoveField(
            model_name="qiraa",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="qiraa",
            name="updated_at",
        ),
    ]
