# Generated by Django 6.0.6 on 2026-07-02 07:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_mushaf_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="mushaf",
            name="pdf_original_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Filename of the uploaded PDF (the stored file is renamed to its hash).",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mushaf_created", "Mushaf Created"),
                            ("bounds_set", "Bounds Set"),
                            ("template_saved", "Template Saved"),
                            ("run_finished", "Run Finished"),
                            ("review_saved", "Review Saved"),
                            ("lines_exported", "Lines Exported"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Event details keyed by type, e.g. {'template_type': ...} for template_saved, {'run_id', 'run_number', 'status', 'pages_saved', 'page_range_start', 'page_range_end'} for run_finished, {'page_number': ...} for review_saved.",
                    ),
                ),
                (
                    "mushaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="activity_events", to="api.mushaf"
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Event",
                "verbose_name_plural": "Activity Events",
                "db_table": "activity_event",
            },
        ),
    ]
