# Generated by Django 6.0.6 on 2026-07-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_line_options_alter_segment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingrun',
            name='log_path',
            field=models.CharField(blank=True, default='', help_text="Path (relative to settings.LOG_DIR) of this run's detailed log file.", max_length=255),
        ),
    ]
