# Generated by Django 6.0.6 on 2026-08-14 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_mushaf_owner_activityevent_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushaf',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Shown on the gallery card — what this mushaf is and how complete the work is.'),
        ),
        migrations.AddField(
            model_name='mushaf',
            name='duplicated_from',
            field=models.ForeignKey(blank=True, help_text='The gallery mushaf this was copied from. SET_NULL so a copy outlives its source being deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='api.mushaf'),
        ),
        migrations.AddField(
            model_name='mushaf',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mushaf',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('published', 'Published')], default='private', help_text='Published mushafs appear in the public gallery and can be duplicated by anyone.', max_length=16),
        ),
    ]
