# Generated by Django 6.0.6 on 2026-08-17 13:34

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_mushaf_publishing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page_range_start", models.PositiveSmallIntegerField()),
                ("page_range_end", models.PositiveSmallIntegerField()),
                ("total", models.PositiveSmallIntegerField(default=0, help_text="Pages in the requested range.")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("aborted_line_detection", "Aborted (line detection)"),
                            ("cancelled", "Cancelled"),
                            ("error", "Error"),
                            ("interrupted", "Interrupted"),
                        ],
                        default="running",
                        max_length=32,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        default="starting", help_text="starting/rendering/detecting/saving/finished.", max_length=16
                    ),
                ),
                ("current_page", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "pages_saved",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Pages actually written — durable, not an estimate."
                    ),
                ),
                (
                    "cancel_requested",
                    models.BooleanField(
                        default=False,
                        help_text="Polled by the worker between pages. A flag rather than a signal, so any process can set it.",
                    ),
                ),
                (
                    "heartbeat_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last sign of life from the worker. What lets another process tell a long page apart from a worker that died.",
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stopped_on_page",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Page the run came to rest on — what 'Resume from here' uses.", null=True
                    ),
                ),
                ("abort_info", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("end_sura", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("end_aya", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("log_url", models.CharField(blank=True, default="", max_length=255)),
                (
                    "mushaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="process_jobs", to="api.mushaf"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="api.processingrun",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who asked for this run; used for the per-user concurrency cap.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="process_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Job",
                "verbose_name_plural": "Process Jobs",
                "db_table": "process_job",
                "indexes": [models.Index(fields=["mushaf", "-started_at"], name="process_job_mushaf_recent")],
            },
        ),
    ]
