# Generated by Django 6.0.6 on 2026-08-18 10:38

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_process_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushaf',
            name='export_uniform_size',
            field=models.BooleanField(default=False, help_text="Pad every exported line PNG on a page out to the size of that page's largest line, with transparent space. Nothing is ever cropped."),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_png',
            field=models.ImageField(help_text='Final PNG path after coordinates + erase; set on export', null=True, upload_to=api.models.line_png_path),
        ),
        migrations.AlterField(
            model_name='mushaf',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='mushaf',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Small render of the first physical PDF page (the cover), for list views.', null=True, upload_to=api.models.thumbnail_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(upload_to=api.models.template_path),
        ),
    ]
