# Generated by Django 6.0.6 on 2026-09-01 09:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_mushaf_qiraa_to_rawi'),
        ('quran', '0004_word_aya'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word_order', models.PositiveSmallIntegerField(help_text='Position on the line; 1 is the rightmost word.')),
                ('end_x', models.PositiveIntegerField(help_text='Page x where the word ends — its LEFT edge, since Arabic runs right to left.')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='api.line')),
                ('word', models.ForeignKey(help_text='Which word of the Quran this is, by its global index.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quran.word')),
            ],
            options={
                'verbose_name': 'Line Word',
                'verbose_name_plural': 'Line Words',
                'db_table': 'line_word',
                'ordering': ('word_order',),
                'constraints': [models.UniqueConstraint(fields=('line', 'word_order'), name='unique_line_word_order')],
            },
        ),
    ]
