# Generated by Django 6.0.6 on 2026-09-01 11:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_line_word'),
        ('quran', '0004_word_aya'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineWordStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('exact', 'Exact'), ('scored', 'Scored'), ('partial', 'Partial'), ('unresolved', 'Unresolved')], max_length=16)),
                ('reason', models.TextField(blank=True, default='', help_text="Why it is not exact, e.g. '2 word(s) off-count; 3 equal-cost readings'.")),
                ('deviations', models.PositiveSmallIntegerField(default=0, help_text='Words that closed on more or fewer ink blobs than their spelling demands.')),
                ('ties', models.PositiveSmallIntegerField(default=0, help_text='Equal-cost readings the parser could not separate.')),
                ('edited', models.BooleanField(default=False, help_text="A human has corrected this line since; the engine's verdict is no longer the truth about it.")),
            ],
            options={
                'verbose_name': 'Line Word Status',
                'verbose_name_plural': 'Line Word Statuses',
                'db_table': 'line_word_status',
            },
        ),
        migrations.AlterModelOptions(
            name='lineword',
            options={'ordering': ('-end_x',), 'verbose_name': 'Line Word', 'verbose_name_plural': 'Line Words'},
        ),
        migrations.RemoveConstraint(
            model_name='lineword',
            name='unique_line_word_order',
        ),
        migrations.AddField(
            model_name='processjob',
            name='kind',
            field=models.CharField(choices=[('detection', 'Page detection'), ('words', 'Word boundaries')], default='detection', help_text='Which engine this run drives. Detection walks pages; words walks lines.', max_length=16),
        ),
        migrations.AddField(
            model_name='processjob',
            name='lines_done',
            field=models.PositiveIntegerField(blank=True, help_text='Word runs only: lines written so far. Detection counts pages instead.', null=True),
        ),
        migrations.AddField(
            model_name='processjob',
            name='start_aya',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processjob',
            name='start_sura',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='type',
            field=models.CharField(choices=[('mushaf_created', 'Mushaf Created'), ('bounds_set', 'Bounds Set'), ('template_saved', 'Template Saved'), ('run_finished', 'Run Finished'), ('review_saved', 'Review Saved'), ('lines_exported', 'Lines Exported'), ('words_detected', 'Words Detected'), ('words_edited', 'Words Edited')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lineword',
            name='word',
            field=models.ForeignKey(help_text='Which word of the Quran this is, by its global index. Null where this mushaf carries a word the stored text does not have.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quran.word'),
        ),
        migrations.AddConstraint(
            model_name='lineword',
            constraint=models.UniqueConstraint(fields=('line', 'word'), name='unique_line_word'),
        ),
        migrations.AddConstraint(
            model_name='lineword',
            constraint=models.UniqueConstraint(fields=('line', 'end_x'), name='unique_line_word_end'),
        ),
        migrations.AddField(
            model_name='linewordstatus',
            name='line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='word_status', to='api.line'),
        ),
        migrations.RemoveField(
            model_name='lineword',
            name='word_order',
        ),
    ]
