# Generated by Django 6.0.6 on 2026-09-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_process_job_log_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushaf',
            name='ijam_mode',
            field=models.CharField(choices=[('report', 'Report a word that lost a dot'), ('ignore', 'Do not check dots')], default='report', help_text="Whether word detection checks each word against the dots its spelling expects. The stored text describes one convention: Maghribi puts fa's dot below where it puts it above, and a mushaf may leave a final ya undotted, so on those every such word reads as short. Set this to 'ignore' there. It is a fact about the printing, like the riwaya, and is not guessed.", max_length=16),
        ),
    ]
