# Generated by Django 6.0.6 on 2026-09-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_mushaf_ijam_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('sura_header', 'Sura Header'), ('aya_separator', 'Aya Separator'), ('sajda', 'Sajda Symbol'), ('rub_hizb', "Rub' al-Hizb Symbol")], default='sura_header', max_length=16),
        ),
    ]
