# Generated by Django 6.0.6 on 2026-09-26 07:25

import uuid

import django.db.models.deletion
from django.db import migrations, models

import api.models


def preserve_legacy_boundaries(apps, schema_editor):
    """Archive every hand-corrected line's boundaries, as the running app will.

    Before this migration a re-processed page took its corrected words with it; from
    here on ``api.signals`` archives them first. This covers the corrections already
    made. Boundaries only — no blob was ever labelled, so none is invented.
    """
    alias = schema_editor.connection.alias
    Line = apps.get_model("api", "Line")
    Review = apps.get_model("api", "CalibrationReview")
    Revision = apps.get_model("api", "CalibrationRevision")
    by_page: dict[tuple, list] = {}
    for line in (
        Line.objects.using(alias)
        .filter(models.Q(word_status__edited=True) | models.Q(word_status__isnull=True, words__isnull=False))
        .distinct()
        .select_related("page")
        .prefetch_related("words")
        .order_by("line_number")
    ):
        key = (line.page.mushaf_id, line.page.page_number)
        by_page.setdefault(key, []).append(
            {
                "line_number": line.line_number,
                "line_id": str(line.pk),
                "words": [
                    {"word_id": word.word_id, "position": word.position, "start_x": word.start_x, "end_x": word.end_x}
                    for word in line.words.all()
                ],
            }
        )
    for (mushaf_id, page_number), lines in by_page.items():
        payload = {"legacy_lines": lines}
        review = Review.objects.using(alias).create(
            mushaf_id=mushaf_id, page_number=page_number, revision=1, payload=payload
        )
        Revision.objects.using(alias).create(review=review, number=1, kind="legacy", payload=payload)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_template_symbol_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("mushaf_created", "Mushaf Created"),
                    ("bounds_set", "Bounds Set"),
                    ("template_saved", "Template Saved"),
                    ("run_finished", "Run Finished"),
                    ("review_saved", "Review Saved"),
                    ("lines_exported", "Lines Exported"),
                    ("words_detected", "Words Detected"),
                    ("words_edited", "Words Edited"),
                    ("calibration_saved", "Calibration Saved"),
                    ("calibration_confirmed", "Calibration Confirmed"),
                    ("calibration_processed", "Calibration Processed"),
                    ("calibration_evaluated", "Calibration Evaluated"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="processjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("detection", "Page detection"),
                    ("words", "Word boundaries"),
                    ("calibration", "Calibration page"),
                ],
                default="detection",
                help_text="Which engine this run drives. Detection walks pages; words walks lines.",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="CalibrationReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page_number", models.PositiveSmallIntegerField()),
                ("revision", models.PositiveIntegerField(default=0)),
                ("confirmed_revision", models.PositiveIntegerField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "mushaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="calibration_reviews", to="api.mushaf"
                    ),
                ),
            ],
            options={
                "verbose_name": "Calibration Review",
                "verbose_name_plural": "Calibration Reviews",
                "db_table": "calibration_review",
            },
        ),
        migrations.CreateModel(
            name="CalibrationRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("processed", "Processed"),
                            ("confirmed", "Confirmed"),
                            ("legacy", "Legacy boundaries"),
                        ],
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="api.calibrationreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calibration Revision",
                "verbose_name_plural": "Calibration Revisions",
                "db_table": "calibration_revision",
                "ordering": ("number",),
            },
        ),
        migrations.CreateModel(
            name="CalibrationSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page_number", models.PositiveSmallIntegerField()),
                ("line_number", models.PositiveSmallIntegerField()),
                ("source_line_id", models.UUIDField(blank=True, null=True)),
                ("fingerprint", models.CharField(max_length=64)),
                ("metadata", models.JSONField(default=dict)),
                ("image", models.FileField(max_length=255, upload_to=api.models.calibration_file_path)),
                ("labels", models.FileField(max_length=255, upload_to=api.models.calibration_file_path)),
                (
                    "mushaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibration_snapshots",
                        to="api.mushaf",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calibration Snapshot",
                "verbose_name_plural": "Calibration Snapshots",
                "db_table": "calibration_snapshot",
            },
        ),
        migrations.CreateModel(
            name="CalibrationProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("signature", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("mode", models.CharField(default="shadow", max_length=16)),
                (
                    "mushaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibration_profiles",
                        to="api.mushaf",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calibration Profile",
                "verbose_name_plural": "Calibration Profiles",
                "db_table": "calibration_profile",
                "constraints": [
                    models.UniqueConstraint(fields=("mushaf", "signature"), name="unique_calibration_profile")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="calibrationreview",
            constraint=models.UniqueConstraint(fields=("mushaf", "page_number"), name="unique_calibration_review"),
        ),
        migrations.AddConstraint(
            model_name="calibrationrevision",
            constraint=models.UniqueConstraint(fields=("review", "number"), name="unique_calibration_revision"),
        ),
        migrations.AddConstraint(
            model_name="calibrationrevision",
            constraint=models.UniqueConstraint(fields=("review", "request_id"), name="unique_calibration_request"),
        ),
        migrations.AddConstraint(
            model_name="calibrationsnapshot",
            constraint=models.UniqueConstraint(fields=("mushaf", "fingerprint"), name="unique_calibration_snapshot"),
        ),
        migrations.RunPython(preserve_legacy_boundaries, migrations.RunPython.noop),
    ]
