# Generated by Django 6.0.6 on 2026-09-27 14:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_calibration_persistence"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalibrationSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("experimental", models.BooleanField(default=False)),
                (
                    "mushaf",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibration_settings",
                        to="api.mushaf",
                    ),
                ),
            ],
            options={
                "db_table": "calibration_settings",
            },
        ),
    ]
