/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as LineReviewRouteImport } from './routes/line-review'
import { Route as FinalizeRouteImport } from './routes/finalize'
import { Route as CutReviewRouteImport } from './routes/cut-review'
import { Route as IndexRouteImport } from './routes/index'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const LineReviewRoute = LineReviewRouteImport.update({
  id: '/line-review',
  path: '/line-review',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalizeRoute = FinalizeRouteImport.update({
  id: '/finalize',
  path: '/finalize',
  getParentRoute: () => rootRouteImport,
} as any)
const CutReviewRoute = CutReviewRouteImport.update({
  id: '/cut-review',
  path: '/cut-review',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cut-review': typeof CutReviewRoute
  '/finalize': typeof FinalizeRoute
  '/line-review': typeof LineReviewRoute
  '/review': typeof ReviewRoute
  '/upload': typeof UploadRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cut-review': typeof CutReviewRoute
  '/finalize': typeof FinalizeRoute
  '/line-review': typeof LineReviewRoute
  '/review': typeof ReviewRoute
  '/upload': typeof UploadRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cut-review': typeof CutReviewRoute
  '/finalize': typeof FinalizeRoute
  '/line-review': typeof LineReviewRoute
  '/review': typeof ReviewRoute
  '/upload': typeof UploadRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cut-review'
    | '/finalize'
    | '/line-review'
    | '/review'
    | '/upload'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cut-review'
    | '/finalize'
    | '/line-review'
    | '/review'
    | '/upload'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/cut-review'
    | '/finalize'
    | '/line-review'
    | '/review'
    | '/upload'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CutReviewRoute: typeof CutReviewRoute
  FinalizeRoute: typeof FinalizeRoute
  LineReviewRoute: typeof LineReviewRoute
  ReviewRoute: typeof ReviewRoute
  UploadRoute: typeof UploadRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line-review': {
      id: '/line-review'
      path: '/line-review'
      fullPath: '/line-review'
      preLoaderRoute: typeof LineReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finalize': {
      id: '/finalize'
      path: '/finalize'
      fullPath: '/finalize'
      preLoaderRoute: typeof FinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cut-review': {
      id: '/cut-review'
      path: '/cut-review'
      fullPath: '/cut-review'
      preLoaderRoute: typeof CutReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CutReviewRoute: CutReviewRoute,
  FinalizeRoute: FinalizeRoute,
  LineReviewRoute: LineReviewRoute,
  ReviewRoute: ReviewRoute,
  UploadRoute: UploadRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
