/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MushafsMushafIdRouteImport } from './routes/mushafs.$mushafId'
import { Route as MushafsMushafIdIndexRouteImport } from './routes/mushafs.$mushafId.index'
import { Route as MushafsMushafIdTemplatesRouteImport } from './routes/mushafs.$mushafId.templates'
import { Route as MushafsMushafIdSetupRouteImport } from './routes/mushafs.$mushafId.setup'
import { Route as MushafsMushafIdReviewRouteImport } from './routes/mushafs.$mushafId.review'
import { Route as MushafsMushafIdProcessRouteImport } from './routes/mushafs.$mushafId.process'
import { Route as MushafsMushafIdFinalizeRouteImport } from './routes/mushafs.$mushafId.finalize'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MushafsMushafIdRoute = MushafsMushafIdRouteImport.update({
  id: '/mushafs/$mushafId',
  path: '/mushafs/$mushafId',
  getParentRoute: () => rootRouteImport,
} as any)
const MushafsMushafIdIndexRoute = MushafsMushafIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MushafsMushafIdRoute,
} as any)
const MushafsMushafIdTemplatesRoute =
  MushafsMushafIdTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => MushafsMushafIdRoute,
  } as any)
const MushafsMushafIdSetupRoute = MushafsMushafIdSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => MushafsMushafIdRoute,
} as any)
const MushafsMushafIdReviewRoute = MushafsMushafIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => MushafsMushafIdRoute,
} as any)
const MushafsMushafIdProcessRoute = MushafsMushafIdProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => MushafsMushafIdRoute,
} as any)
const MushafsMushafIdFinalizeRoute = MushafsMushafIdFinalizeRouteImport.update({
  id: '/finalize',
  path: '/finalize',
  getParentRoute: () => MushafsMushafIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mushafs/$mushafId': typeof MushafsMushafIdRouteWithChildren
  '/mushafs/$mushafId/finalize': typeof MushafsMushafIdFinalizeRoute
  '/mushafs/$mushafId/process': typeof MushafsMushafIdProcessRoute
  '/mushafs/$mushafId/review': typeof MushafsMushafIdReviewRoute
  '/mushafs/$mushafId/setup': typeof MushafsMushafIdSetupRoute
  '/mushafs/$mushafId/templates': typeof MushafsMushafIdTemplatesRoute
  '/mushafs/$mushafId/': typeof MushafsMushafIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mushafs/$mushafId/finalize': typeof MushafsMushafIdFinalizeRoute
  '/mushafs/$mushafId/process': typeof MushafsMushafIdProcessRoute
  '/mushafs/$mushafId/review': typeof MushafsMushafIdReviewRoute
  '/mushafs/$mushafId/setup': typeof MushafsMushafIdSetupRoute
  '/mushafs/$mushafId/templates': typeof MushafsMushafIdTemplatesRoute
  '/mushafs/$mushafId': typeof MushafsMushafIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mushafs/$mushafId': typeof MushafsMushafIdRouteWithChildren
  '/mushafs/$mushafId/finalize': typeof MushafsMushafIdFinalizeRoute
  '/mushafs/$mushafId/process': typeof MushafsMushafIdProcessRoute
  '/mushafs/$mushafId/review': typeof MushafsMushafIdReviewRoute
  '/mushafs/$mushafId/setup': typeof MushafsMushafIdSetupRoute
  '/mushafs/$mushafId/templates': typeof MushafsMushafIdTemplatesRoute
  '/mushafs/$mushafId/': typeof MushafsMushafIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mushafs/$mushafId'
    | '/mushafs/$mushafId/finalize'
    | '/mushafs/$mushafId/process'
    | '/mushafs/$mushafId/review'
    | '/mushafs/$mushafId/setup'
    | '/mushafs/$mushafId/templates'
    | '/mushafs/$mushafId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mushafs/$mushafId/finalize'
    | '/mushafs/$mushafId/process'
    | '/mushafs/$mushafId/review'
    | '/mushafs/$mushafId/setup'
    | '/mushafs/$mushafId/templates'
    | '/mushafs/$mushafId'
  id:
    | '__root__'
    | '/'
    | '/mushafs/$mushafId'
    | '/mushafs/$mushafId/finalize'
    | '/mushafs/$mushafId/process'
    | '/mushafs/$mushafId/review'
    | '/mushafs/$mushafId/setup'
    | '/mushafs/$mushafId/templates'
    | '/mushafs/$mushafId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MushafsMushafIdRoute: typeof MushafsMushafIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mushafs/$mushafId': {
      id: '/mushafs/$mushafId'
      path: '/mushafs/$mushafId'
      fullPath: '/mushafs/$mushafId'
      preLoaderRoute: typeof MushafsMushafIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mushafs/$mushafId/': {
      id: '/mushafs/$mushafId/'
      path: '/'
      fullPath: '/mushafs/$mushafId/'
      preLoaderRoute: typeof MushafsMushafIdIndexRouteImport
      parentRoute: typeof MushafsMushafIdRoute
    }
    '/mushafs/$mushafId/templates': {
      id: '/mushafs/$mushafId/templates'
      path: '/templates'
      fullPath: '/mushafs/$mushafId/templates'
      preLoaderRoute: typeof MushafsMushafIdTemplatesRouteImport
      parentRoute: typeof MushafsMushafIdRoute
    }
    '/mushafs/$mushafId/setup': {
      id: '/mushafs/$mushafId/setup'
      path: '/setup'
      fullPath: '/mushafs/$mushafId/setup'
      preLoaderRoute: typeof MushafsMushafIdSetupRouteImport
      parentRoute: typeof MushafsMushafIdRoute
    }
    '/mushafs/$mushafId/review': {
      id: '/mushafs/$mushafId/review'
      path: '/review'
      fullPath: '/mushafs/$mushafId/review'
      preLoaderRoute: typeof MushafsMushafIdReviewRouteImport
      parentRoute: typeof MushafsMushafIdRoute
    }
    '/mushafs/$mushafId/process': {
      id: '/mushafs/$mushafId/process'
      path: '/process'
      fullPath: '/mushafs/$mushafId/process'
      preLoaderRoute: typeof MushafsMushafIdProcessRouteImport
      parentRoute: typeof MushafsMushafIdRoute
    }
    '/mushafs/$mushafId/finalize': {
      id: '/mushafs/$mushafId/finalize'
      path: '/finalize'
      fullPath: '/mushafs/$mushafId/finalize'
      preLoaderRoute: typeof MushafsMushafIdFinalizeRouteImport
      parentRoute: typeof MushafsMushafIdRoute
    }
  }
}

interface MushafsMushafIdRouteChildren {
  MushafsMushafIdFinalizeRoute: typeof MushafsMushafIdFinalizeRoute
  MushafsMushafIdProcessRoute: typeof MushafsMushafIdProcessRoute
  MushafsMushafIdReviewRoute: typeof MushafsMushafIdReviewRoute
  MushafsMushafIdSetupRoute: typeof MushafsMushafIdSetupRoute
  MushafsMushafIdTemplatesRoute: typeof MushafsMushafIdTemplatesRoute
  MushafsMushafIdIndexRoute: typeof MushafsMushafIdIndexRoute
}

const MushafsMushafIdRouteChildren: MushafsMushafIdRouteChildren = {
  MushafsMushafIdFinalizeRoute: MushafsMushafIdFinalizeRoute,
  MushafsMushafIdProcessRoute: MushafsMushafIdProcessRoute,
  MushafsMushafIdReviewRoute: MushafsMushafIdReviewRoute,
  MushafsMushafIdSetupRoute: MushafsMushafIdSetupRoute,
  MushafsMushafIdTemplatesRoute: MushafsMushafIdTemplatesRoute,
  MushafsMushafIdIndexRoute: MushafsMushafIdIndexRoute,
}

const MushafsMushafIdRouteWithChildren = MushafsMushafIdRoute._addFileChildren(
  MushafsMushafIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MushafsMushafIdRoute: MushafsMushafIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
